/**
 * Comprehensive emoji shortcode map: name -> emoji
 * Used by MentionInput for `:shortcode:` autocomplete.
 * Organized by category with common aliases.
 */
export const EMOJI_SHORTCODES: Record<string, string> = {
    // ── Smileys & Emotion ──────────────────────────────────────────
    grinning: "😀", grin: "😁", joy: "😂", rofl: "🤣", smiley: "😃",
    smile: "😄", sweat_smile: "😅", laughing: "😆", wink: "😉",
    blush: "😊", yum: "😋", heart_eyes: "😍", star_struck: "🤩",
    kiss: "😘", kissing: "😗", kissing_heart: "😘", kissing_closed_eyes: "😚",
    kissing_smiling_eyes: "😙", relaxed: "☺️", stuck_out_tongue: "😛",
    stuck_out_tongue_winking_eye: "😜", zany: "🤪", tongue: "😛",
    stuck_out_tongue_closed_eyes: "😝", money_mouth: "🤑",
    hugs: "🤗", hand_over_mouth: "🤭", shush: "🤫", thinking: "🤔",
    zipper_mouth: "🤐", raised_eyebrow: "🤨", neutral: "😐",
    expressionless: "😑", no_mouth: "😶", cloud_face: "😶‍🌫️",
    smirk: "😏", unamused: "😒", rolling_eyes: "🙄", grimacing: "😬",
    exhale: "😮‍💨", lying: "🤥", relieved: "😌", pensive: "😔",
    sleepy: "😪", drooling: "🤤", sleeping: "😴", mask: "😷",
    thermometer_face: "🤒", bandage_face: "🤕", nauseated: "🤢",
    vomiting: "🤮", sneezing: "🤧", hot: "🥵", cold: "🥶",
    woozy: "🥴", dizzy_face: "😵", exploding_head: "🤯",
    cowboy: "🤠", party: "🥳", disguised: "🥸", sunglasses: "😎",
    nerd: "🤓", monocle: "🧐", confused: "😕", worried: "😟",
    slightly_frowning: "🙁", frowning: "☹️", open_mouth: "😮",
    hushed: "😯", astonished: "😲", flushed: "😳", pleading: "🥺",
    holding_back_tears: "🥹", anguished: "😧", fearful: "😨",
    cold_sweat: "😰", disappointed_relieved: "😥", cry: "😢",
    sob: "😭", scream: "😱", confounded: "😖", persevere: "😣",
    disappointed: "😞", sweat: "😓", weary: "😩", tired: "😫",
    yawning: "🥱", angry: "😠", rage: "😡", cursing: "🤬",
    smiling_imp: "😈", imp: "👿", skull: "💀", skull_crossbones: "☠️",
    poop: "💩", clown: "🤡", ogre: "👹", goblin: "👺",
    ghost: "👻", alien: "👽", robot: "🤖", cat_grin: "😸",
    cat_joy: "😹", cat_heart_eyes: "😻", cat_smirk: "😼",
    cat_kiss: "😽", cat_scream: "🙀", cat_cry: "😿", cat_pout: "😾",
    see_no_evil: "🙈", hear_no_evil: "🙉", speak_no_evil: "🙊",
    kiss_mark: "💋", love_letter: "💌", cupid: "💘",
    gift_heart: "💝", sparkling_heart: "💖", growing_heart: "💗",
    beating_heart: "💓", revolving_hearts: "💞", two_hearts: "💕",
    heart_decoration: "💟", heart_exclamation: "❣️", broken_heart: "💔",
    heart_fire: "❤️‍🔥", heart_mend: "❤️‍🩹", heart: "❤️",
    red_heart: "❤️", orange_heart: "🧡", yellow_heart: "💛",
    green_heart: "💚", blue_heart: "💙", purple_heart: "💜",
    brown_heart: "🤎", black_heart: "🖤", white_heart: "🤍",
    pink_heart: "🩷", light_blue_heart: "🩵", grey_heart: "🩶",
    hundred: "💯", "100": "💯", anger: "💢", boom: "💥", collision: "💥",
    sweat_drops: "💦", dash: "💨", hole: "🕳️", bomb: "💣",
    speech_balloon: "💬", thought_balloon: "💭", zzz: "💤",
    wave: "👋",

    // ── Gestures & People ──────────────────────────────────────────
    raised_back_hand: "🤚", raised_hand: "✋", vulcan: "🖖",
    ok_hand: "👌", ok: "👌", pinched: "🤌", pinch: "🤏",
    peace: "✌️", v: "✌️", crossed_fingers: "🤞", love_you: "🤟",
    rock: "🤘", call_me: "🤙", shaka: "🤙",
    point_left: "👈", point_right: "👉", point_up_2: "👆",
    middle_finger: "🖕", point_down: "👇", point_up: "☝️",
    thumbsup: "👍", thumbs_up: "👍", "+1": "👍", up: "👍",
    thumbsdown: "👎", thumbs_down: "👎", "-1": "👎", down: "👎",
    fist: "✊", punch: "👊", fist_left: "🤛", fist_right: "🤜",
    clap: "👏", raised_hands: "🙌", open_hands: "👐",
    palms_up: "🤲", handshake: "🤝", pray: "🙏", namaste: "🙏",
    writing_hand: "✍️", nail_care: "💅", selfie: "🤳",
    muscle: "💪", flex: "💪", strong: "💪",
    leg: "🦵", foot: "🦶", ear: "👂", nose: "👃",
    brain: "🧠", tooth: "🦷", bone: "🦴", eyes: "👀",
    eye: "👁️", tongue_out: "👅", lips: "👄", biting_lip: "🫦",
    baby: "👶", child: "🧒", boy: "👦", girl: "👧",
    person: "🧑", man: "👨", woman: "👩", older_person: "🧓",

    // ── Animals & Nature ───────────────────────────────────────────
    dog: "🐶", cat: "🐱", mouse: "🐭", hamster: "🐹",
    rabbit: "🐰", fox: "🦊", bear: "🐻", panda: "🐼",
    polar_bear: "🐻‍❄️", koala: "🐨", tiger: "🐯", lion: "🦁",
    cow: "🐮", pig: "🐷", pig_nose: "🐽", frog: "🐸",
    monkey_face: "🐵", monkey: "🐒", gorilla: "🦍", orangutan: "🦧",
    chicken: "🐔", penguin: "🐧", bird: "🐦", eagle: "🦅",
    duck: "🦆", swan: "🦢", owl: "🦉", dodo: "🦤",
    flamingo: "🦩", peacock: "🦚", parrot: "🦜", bat: "🦇",
    wolf: "🐺", boar: "🐗", horse: "🐴", unicorn: "🦄",
    bee: "🐝", honeybee: "🐝", bug: "🐛", butterfly: "🦋",
    snail: "🐌", ladybug: "🐞", ant: "🐜", cricket: "🦗",
    spider: "🕷️", scorpion: "🦂", mosquito: "🦟",
    turtle: "🐢", snake: "🐍", lizard: "🦎", t_rex: "🦖",
    sauropod: "🦕", octopus: "🐙", squid: "🦑",
    shrimp: "🦐", lobster: "🦞", crab: "🦀",
    blowfish: "🐡", tropical_fish: "🐠", fish: "🐟",
    dolphin: "🐬", whale: "🐳", shark: "🦈",
    crocodile: "🐊", leopard: "🐆", zebra: "🦓", elephant: "🐘",
    rhino: "🦏", hippo: "🦛", camel: "🐫", giraffe: "🦒",
    kangaroo: "🦘", deer: "🦌", llama: "🦙", sloth: "🦥",
    otter: "🦦", skunk: "🦨", raccoon: "🦝", hedgehog: "🦔",
    dog2: "🐕", cat2: "🐈", rooster: "🐓", turkey: "🦃",
    ram: "🐏", sheep: "🐑", goat: "🐐", pig2: "🐖",
    paw_prints: "🐾",
    bouquet: "💐", cherry_blossom: "🌸", tulip: "🌷",
    rose: "🌹", wilted_flower: "🥀", sunflower: "🌻",
    blossom: "🌼", hibiscus: "🌺", lotus: "🪷",
    seedling: "🌱", evergreen_tree: "🌲", deciduous_tree: "🌳",
    palm_tree: "🌴", cactus: "🌵", herb: "🌿",
    shamrock: "☘️", four_leaf_clover: "🍀", maple_leaf: "🍁",
    fallen_leaf: "🍂", leaves: "🍃", mushroom: "🍄",

    // ── Food & Drink ───────────────────────────────────────────────
    grapes: "🍇", melon: "🍈", watermelon: "🍉", tangerine: "🍊",
    lemon: "🍋", banana: "🍌", pineapple: "🍍", mango: "🥭",
    apple: "🍎", green_apple: "🍏", pear: "🍐", peach: "🍑",
    cherries: "🍒", strawberry: "🍓", blueberries: "🫐", kiwi: "🥝",
    tomato: "🍅", coconut: "🥥", avocado: "🥑", eggplant: "🍆",
    potato: "🥔", carrot: "🥕", corn: "🌽", hot_pepper: "🌶️",
    cucumber: "🥒", broccoli: "🥦", garlic: "🧄", onion: "🧅",
    peanuts: "🥜", chestnut: "🌰", bread: "🍞", croissant: "🥐",
    baguette: "🥖", pretzel: "🥨", bagel: "🥯", pancakes: "🥞",
    waffle: "🧇", cheese: "🧀", egg: "🥚", cooking: "🍳",
    bacon: "🥓", steak: "🥩", poultry_leg: "🍗",
    hamburger: "🍔", burger: "🍔", fries: "🍟", pizza: "🍕",
    hotdog: "🌭", sandwich: "🥪", taco: "🌮", burrito: "🌯",
    tamale: "🫔", falafel: "🧆", flatbread: "🫓",
    sushi: "🍣", bento: "🍱", curry: "🍛", ramen: "🍜",
    spaghetti: "🍝", dumpling: "🥟", fried_shrimp: "🍤",
    rice_ball: "🍙", rice: "🍚", cake: "🎂", birthday: "🎂",
    pie: "🥧", cupcake: "🧁", cookie: "🍪", chocolate: "🍫",
    candy: "🍬", lollipop: "🍭", donut: "🍩", doughnut: "🍩",
    ice_cream: "🍨", icecream: "🍦", shaved_ice: "🍧",
    honey: "🍯", milk: "🥛", coffee: "☕", tea: "🍵",
    mate: "🧉", bubble_tea: "🧋", juice: "🧃",
    beer: "🍺", beers: "🍻", clinking_glasses: "🥂", wine: "🍷",
    tumbler: "🥃", cocktail: "🍸", tropical_drink: "🍹",
    champagne: "🍾", sake: "🍶",

    // ── Travel & Places ────────────────────────────────────────────
    earth_americas: "🌎", earth_africa: "🌍", earth_asia: "🌏",
    globe: "🌐", world_map: "🗺️", compass: "🧭",
    mountain: "⛰️", volcano: "🌋", camping: "🏕️",
    beach: "🏖️", desert: "🏜️", island: "🏝️",
    stadium: "🏟️", building: "🏢", house: "🏠",
    church: "⛪", mosque: "🕌", temple: "🛕",
    castle: "🏰", statue_of_liberty: "🗽", tokyo_tower: "🗼",
    car: "🚗", taxi: "🚕", bus: "🚌", ambulance: "🚑",
    fire_engine: "🚒", police_car: "🚓", truck: "🚚",
    motorcycle: "🏍️", bicycle: "🚲", scooter: "🛴",
    skateboard: "🛹", airplane: "✈️", helicopter: "🚁",
    rocket: "🚀", satellite: "🛰️", ufo: "🛸",
    ship: "🚢", sailboat: "⛵", speedboat: "🚤",
    anchor: "⚓", fuelpump: "⛽",

    // ── Activities ─────────────────────────────────────────────────
    soccer: "⚽", basketball: "🏀", football: "🏈", baseball: "⚾",
    tennis: "🎾", volleyball: "🏐", rugby: "🏉",
    pool_8ball: "🎱", ping_pong: "🏓", badminton: "🏸",
    hockey: "🏒", golf: "⛳", bow_and_arrow: "🏹",
    fishing: "🎣", diving: "🤿", boxing: "🥊", martial_arts: "🥋",
    skiing: "⛷️", snowboarding: "🏂", surfing: "🏄",
    swimming: "🏊", climbing: "🧗", yoga: "🧘",
    trophy: "🏆", medal: "🏅", gold_medal: "🥇",
    silver_medal: "🥈", bronze_medal: "🥉",
    ticket: "🎫", circus_tent: "🎪",
    art: "🎨", palette: "🎨", performing_arts: "🎭",
    microphone: "🎤", headphones: "🎧", musical_note: "🎵",
    notes: "🎶", saxophone: "🎷", guitar: "🎸",
    piano: "🎹", trumpet: "🎺", violin: "🎻", drum: "🥁",
    dice: "🎲", chess: "♟️", dart: "🎯",
    bowling: "🎳", video_game: "🎮", joystick: "🕹️",
    slot_machine: "🎰", jigsaw: "🧩",

    // ── Objects ─────────────────────────────────────────────────────
    watch: "⌚", phone: "📱", mobile: "📱", computer: "💻",
    laptop: "💻", keyboard: "⌨️", desktop: "🖥️", printer: "🖨️",
    mouse_computer: "🖱️", cd: "💿", floppy: "💾", dvd: "📀",
    camera: "📷", video_camera: "📹", movie_camera: "🎥",
    tv: "📺", radio: "📻", loudspeaker: "📢", megaphone: "📣",
    bell: "🔔", no_bell: "🔕", speaker: "🔈", mute: "🔇",
    battery: "🔋", plug: "🔌", bulb: "💡", flashlight: "🔦",
    candle: "🕯️", lamp: "🪔",
    money_bag: "💰", money: "💰", dollar: "💵", euro: "💶",
    yen: "💴", pound: "💷", coin: "🪙", credit_card: "💳",
    gem: "💎", diamond: "💎", ring: "💍", crown: "👑",
    tophat: "🎩", glasses: "👓", necktie: "👔",
    tshirt: "👕", jeans: "👖", dress: "👗",
    key: "🔑", old_key: "🗝️", lock: "🔒", unlock: "🔓",
    hammer: "🔨", axe: "🪓", wrench: "🔧", screwdriver: "🪛",
    gear: "⚙️", link: "🔗", chain: "⛓️", magnet: "🧲",
    scissors: "✂️", paperclip: "📎", pushpin: "📌",
    pen: "🖊️", pencil: "✏️", crayon: "🖍️",
    memo: "📝", notebook: "📓", book: "📖", books: "📚",
    scroll: "📜", newspaper: "📰",
    envelope: "✉️", email: "📧", mailbox: "📫",
    package: "📦", label: "🏷️", bookmark: "🔖",
    gift: "🎁", present: "🎁", balloon: "🎈", tada: "🎉",
    confetti: "🎊", ribbon: "🎀", christmas_tree: "🎄",
    fireworks: "🎆", sparkler: "🎇", firecracker: "🧨",

    // ── Symbols & Signs ────────────────────────────────────────────
    fire: "🔥", lit: "🔥", flame: "🔥",
    star: "⭐", star2: "🌟", sparkles: "✨", glowing_star: "🌟",
    zap: "⚡", lightning: "⚡", thunder: "⚡",
    comet: "☄️", snowflake: "❄️", wind: "🌬️",
    rainbow: "🌈", sun: "☀️", sunny: "☀️",
    cloud: "☁️", rain: "🌧️", snow: "🌨️", umbrella: "☂️",
    moon: "🌙", crescent_moon: "🌙", full_moon: "🌕",
    new_moon: "🌑", first_quarter_moon: "🌓",
    check: "✅", white_check: "✅", heavy_check: "✔️",
    x: "❌", cross: "❌", cross_mark: "❌",
    question: "❓", grey_question: "❔",
    exclamation: "❗", grey_exclamation: "❕",
    bangbang: "‼️", interrobang: "⁉️",
    warning: "⚠️", caution: "⚠️",
    no_entry: "⛔", prohibited: "🚫", stop: "🛑",
    recycle: "♻️", infinity: "♾️",
    trident: "🔱", fleur_de_lis: "⚜️",
    beginner: "🔰", name_badge: "📛",
    o: "⭕", plus: "➕", minus: "➖", multiply: "✖️", divide: "➗",
    curly_loop: "➰", double_loop: "➿",
    arrow_up: "⬆️", arrow_down: "⬇️", arrow_left: "⬅️", arrow_right: "➡️",
    arrow_forward: "▶️", arrow_backward: "◀️", fast_forward: "⏩",
    rewind: "⏪", play_pause: "⏯️",
    new: "🆕", free: "🆓", cool: "🆒", ok_button: "🆗",
    sos: "🆘", up_button: "🆙", vs: "🆚",
    atm: "🏧", parking: "🅿️", wc: "🚾",
    a_button: "🅰️", b_button: "🅱️", ab_button: "🆎", o_button: "🅾️",
    red_circle: "🔴", orange_circle: "🟠", yellow_circle: "🟡",
    green_circle: "🟢", blue_circle: "🔵", purple_circle: "🟣",
    black_circle: "⚫", white_circle: "⚪",
    red_square: "🟥", orange_square: "🟧", yellow_square: "🟨",
    green_square: "🟩", blue_square: "🟦", purple_square: "🟪",
    black_square: "⬛", white_square: "⬜",
    heart_suit: "♥️", diamond_suit: "♦️", club_suit: "♣️", spade_suit: "♠️",

    // ── Flags ──────────────────────────────────────────────────────
    checkered_flag: "🏁", triangular_flag: "🚩", crossed_flags: "🎌",
    pirate_flag: "🏴‍☠️", rainbow_flag: "🏳️‍🌈", trans_flag: "🏳️‍⚧️",
    us: "🇺🇸", usa: "🇺🇸", gb: "🇬🇧", uk: "🇬🇧",
    canada: "🇨🇦", australia: "🇦🇺", germany: "🇩🇪",
    france: "🇫🇷", spain: "🇪🇸", italy: "🇮🇹",
    japan: "🇯🇵", korea: "🇰🇷", china: "🇨🇳",
    india: "🇮🇳", brazil: "🇧🇷", mexico: "🇲🇽",
    russia: "🇷🇺", south_africa: "🇿🇦", nigeria: "🇳🇬",
    egypt: "🇪🇬", uae: "🇦🇪", singapore: "🇸🇬",
    hong_kong: "🇭🇰", taiwan: "🇹🇼", turkiye: "🇹🇷",
    saudi_arabia: "🇸🇦", argentina: "🇦🇷", colombia: "🇨🇴",
    thailand: "🇹🇭", vietnam: "🇻🇳", indonesia: "🇮🇩",
    philippines: "🇵🇭", pakistan: "🇵🇰", bangladesh: "🇧🇩",
    netherlands: "🇳🇱", belgium: "🇧🇪", switzerland: "🇨🇭",
    austria: "🇦🇹", portugal: "🇵🇹", poland: "🇵🇱",
    sweden: "🇸🇪", norway: "🇳🇴", denmark: "🇩🇰",
    finland: "🇫🇮", ireland: "🇮🇪", new_zealand: "🇳🇿",
    ukraine: "🇺🇦", czech: "🇨🇿", greece: "🇬🇷",
    israel: "🇮🇱", kenya: "🇰🇪", ethiopia: "🇪🇹",

    // ── Crypto / Web3 popular ──────────────────────────────────────
    eth: "⟠", ethereum: "⟠", btc: "₿", bitcoin: "₿",
    wagmi: "🚀", gm: "🌅", gn: "🌙", lfg: "🔥",
    diamond_hands: "💎", hodl: "💎", degen: "🎰", ape: "🦍",
    whale2: "🐋", bull: "🐂", to_the_moon: "🌕",
    ngmi: "💀", rug: "🪤", ser: "🎩",

    // ── Common aliases ─────────────────────────────────────────────
    lol: "😂", lmao: "🤣", haha: "😂", hehe: "😄",
    omg: "😱", wow: "🤩", cool_face: "😎", nice: "👍",
    love: "❤️", sad: "😢", happy: "😊", mad: "😡",
    scared: "😨", sick: "🤮", sleep: "😴", shrug: "🤷",
    facepalm: "🤦", salute: "🫡", melting: "🫠",
    peeking: "🫣", dotted_line_face: "🫥",
    upside_down: "🙃", innocent: "😇",
    triumph: "😤", hug: "🤗",
};
